### ISSUE TITLE
Doesn't work with cloudflare R2 and Google cloud run ?

### ISSUE THREAD

**Issue by eashish93** [mjackson/multipart-parser#7]
I tried the example on R2 and gcp  with more than 100MB file. Due to limitation of 32MB on cloudrun and 100MB on R2, this is not working. 
Also, what's the benefit of using this lib over simply using `await req.formData()` on edge server (vercel or cloudflare workers).

<img width="669" alt="Screenshot 2024-08-02 at 5 08 20 PM" src="https://github.com/user-attachments/assets/ad748c33-94cd-4a2c-8220-0d67e530372c">

**Comment by mjackson** [comment]
Depending on which implementation you're using, `req.formData()` will typically need to buffer the entire request in memory instead of streaming it.

HTTP 413 indicates the server rejected the request because the payload was too large. That doesn't have anything to do with this parser. Rather, it's probably a setting you can adjust on your GCP config.
